spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: Rocky2019@@
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    registerWithEureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
