spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: Rocky2019@@
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
